#!/bin/bash

#/etc/rc.d/bftl
# ln -sf /home/cfd/www/beautyofthelove.com/server/bftl /etc/rc.d/

WWW=/home/cfd/www
DIR=$WWW/beautyofthelove.com
export PATH=/home/cfd/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
export NODE_PATH=/home/cfd/lib/node_modules:/usr/lib/node_modules
export NODE=/usr/bin/node

test -x $NODE || exit 0

function start_app {
  NODE_ENV=production nohup "$NODE" "$DIR/app.js" 1>>"$WWW/logs/beautyofthelove.com.log" 2>&1 &
  echo $! > "$WWW/pids/beautyofthelove.pid"
}

function stop_app {
  kill `cat $WWW/pids/beautyofthelove.pid`
}

case $1 in
   start)
      start_app ;;
    stop)
      stop_app ;;
    restart)
      stop_app
      start_app
      ;;
    *)
      echo "usage: bftl {start|stop}" ;;
esac
exit 0


